name: "Test"
on:
  push:
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: 'nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt ."'
