name: "Format nix files"
on:
  push:
jobs:
  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: "Install Nix"
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: "Format with nixpkgs-fmt"
      run: 'nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt ."'
    - name: "Commit formatted files"
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Automated Change
        commit_options: '--no-verify --signoff'
        commit_user_name: GitHub Actions
        commit_author: Author <github-actions@nixos-ansible>
        create_branch: false
        branch: ${{ github.head_ref }}
